"use strict";function asyncGeneratorStep(a,b,c,d,e,f,g){try{var h=a[f](g),i=h.value}catch(a){return void c(a)}h.done?b(i):Promise.resolve(i).then(d,e)}function _asyncToGenerator(a){return function(){var b=this,c=arguments;return new Promise(function(d,e){function f(a){asyncGeneratorStep(h,d,e,f,g,"next",a)}function g(a){asyncGeneratorStep(h,d,e,f,g,"throw",a)}var h=a.apply(b,c);f(void 0)})}}var _require=require("../utils"),readFile=_require.readFile,writeFile=_require.writeFile,FILENAME="../config/database.json";/**
 * @description get getInfo
 * @path        GET /api/v1/getInfo
 */ /**
 * @description get getPersonInfo
 * @path        GET /api/v1/getPersonInfo
 */ /**
 * @description get isCarRegistered
 * @path        POST /api/v1/isCarRegistered
 */ /**
 * @description add addInfo
 * @path        POST /api/v1/addInfo
 */exports.getInsuranceInformation=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.t0=JSON,a.next=4,readFile(FILENAME);case 4:a.t1=a.sent,d=a.t0.parse.call(a.t0,a.t1),c.status(200).json({success:!0,count:d.length,data:d}),a.next=12;break;case 9:a.prev=9,a.t2=a["catch"](0),c.status(500).json({success:!1,error:a.t2});case 12:case"end":return a.stop();}},a,null,[[0,9]])}));return function(){return a.apply(this,arguments)}}(),exports.getPersonInformation=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d,e,f;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:d=b.params.name;try{e=readFile(FILENAME),f=JSON.parse(e).filter(function(a){return a.name.toLowerCase()===d.toLowerCase()}),f.length?c.status(200).json({success:!0,count:f.length,data:f}):c.status(201).json({success:!0,data:[],count:0})}catch(a){c.status(500).json({success:!1,error:a})}case 2:case"end":return a.stop();}},a)}));return function(){return a.apply(this,arguments)}}(),exports.isCarInsuranceInfoRegistered=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d,e,f,g,h;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:d=b.body,e=d.car_model,f=d.car_make_year;try{g=readFile(FILENAME),h=JSON.parse(g).filter(function(a){return a.car_model.toLowerCase()===e.toLowerCase()&&a.car_make_year.toLowerCase()===f.toLowerCase()}),h.length?c.status(200).json({success:!0,count:h.length,data:h}):c.status(201).json({success:!0,data:[],count:0})}catch(a){c.status(500).json({success:!1,error:a})}case 2:case"end":return a.stop();}},a)}));return function(){return a.apply(this,arguments)}}(),exports.addInsuranceInfo=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d,e,f,g,h,i,j,k,l;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:d=b.body,e=d.name,f=d.age,g=d.contact_number,h=d.car_model,i=d.car_make_year,j={name:e,age:f,contact_number:g,car_model:h,car_make_year:i};try{k=JSON.parse(readFile(FILENAME)),l=k.findIndex(function(a){return a.name===j.name}),-1===l?(k.push(j),writeFile(FILENAME,JSON.stringify(k)),c.status(200).json({success:!0,count:1,data:j})):c.status(400).json({success:!1,message:"record already exists!"})}catch(a){c.status(500).json({success:!1,error:a})}case 3:case"end":return a.stop();}},a)}));return function(){return a.apply(this,arguments)}}();