"use strict";function asyncGeneratorStep(a,b,c,d,e,f,g){try{var h=a[f](g),i=h.value}catch(a){return void c(a)}h.done?b(i):Promise.resolve(i).then(d,e)}function _asyncToGenerator(a){return function(){var b=this,c=arguments;return new Promise(function(d,e){function f(a){asyncGeneratorStep(h,d,e,f,g,"next",a)}function g(a){asyncGeneratorStep(h,d,e,f,g,"throw",a)}var h=a.apply(b,c);f(void 0)})}}var InsuranceInfo=require("../models/insuranceInfo");/**
 * @description get getInfo
 * @path        GET /api/v1/cloud/getInfo
 */ /**
 * @description get getPersonInfo
 * @path        GET /api/v1/cloud/getPersonInfo
 */ /**
 * @description get isCarRegistered
 * @path        POST /api/v1/cloud/isCarRegistered
 */ /**
 * @description add addInfo
 * @path        POST /api/v1/cloud/addInfo
 */exports.getInsuranceInformation=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.next=3,InsuranceInfo.find();case 3:return d=a.sent,a.abrupt("return",c.status(200).json({success:!0,count:d.length,data:d}));case 7:return a.prev=7,a.t0=a["catch"](0),a.abrupt("return",c.status(500).json({success:!1,error:a.t0.message||"Server error"}));case 10:case"end":return a.stop();}},a,null,[[0,7]])}));return function(){return a.apply(this,arguments)}}(),exports.getPersonInformation=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.next=3,InsuranceInfo.find(b.body);case 3:return d=a.sent,a.abrupt("return",c.status(200).json({success:!0,count:d.length,data:d}));case 7:return a.prev=7,a.t0=a["catch"](0),a.abrupt("return",c.status(500).json({success:!1,error:a.t0.message||"Server error"}));case 10:case"end":return a.stop();}},a,null,[[0,7]])}));return function(){return a.apply(this,arguments)}}(),exports.isCarInsuranceInfoRegistered=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.next=3,InsuranceInfo.findOne(b.body);case 3:return d=a.sent,a.abrupt("return",c.status(200).json({success:!0,count:d.length,data:d}));case 7:return a.prev=7,a.t0=a["catch"](0),a.abrupt("return",c.status(500).json({success:!1,error:a.t0.message||"Server error"}));case 10:case"end":return a.stop();}},a,null,[[0,7]])}));return function(){return a.apply(this,arguments)}}(),exports.addInsuranceInfo=/*#__PURE__*/function(){var a=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function a(b,c){var d,e;return regeneratorRuntime.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.next=3,InsuranceInfo.create(b.body);case 3:return d=a.sent,a.abrupt("return",c.status(201).json({success:!0,count:d.length,data:d}));case 7:if(a.prev=7,a.t0=a["catch"](0),"ValidationError"!==a.t0.name){a.next=12;break}return e=Object.values(a.t0.errors).map(function(a){return a.message}),a.abrupt("return",c.status(400).json({success:!1,error:e}));case 12:return a.abrupt("return",c.status(500).json({success:!1,error:a.t0.message||"Server error"}));case 13:case"end":return a.stop();}},a,null,[[0,7]])}));return function(){return a.apply(this,arguments)}}();